# Generated by Django 5.0.7 on 2024-08-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='images')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='reg',
            new_name='customer',
        ),
    ]
