# Generated by Django 5.0.7 on 2024-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0002_member_rename_reg_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='usertype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
