# Generated by Django 5.0.7 on 2024-09-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0003_member_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
