# Generated by Django 4.2.14 on 2024-09-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0004_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimage', models.FileField(upload_to='images')),
                ('productname', models.CharField(max_length=255)),
                ('productquantity', models.CharField(max_length=255)),
                ('productdescription', models.CharField(max_length=255)),
                ('productprice', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
