# Generated by Django 4.2.14 on 2024-09-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earphone', models.CharField(max_length=255)),
                ('neckband', models.CharField(max_length=255)),
                ('watch', models.CharField(max_length=255)),
                ('smartphone', models.CharField(max_length=255)),
                ('tablet', models.CharField(max_length=255)),
                ('laptop', models.CharField(max_length=255)),
                ('powerbank', models.CharField(max_length=255)),
                ('covers', models.CharField(max_length=255)),
            ],
        ),
    ]
