# Generated by Django 4.2.14 on 2024-09-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0006_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='covers',
        ),
        migrations.RemoveField(
            model_name='category',
            name='earphone',
        ),
        migrations.RemoveField(
            model_name='category',
            name='laptop',
        ),
        migrations.RemoveField(
            model_name='category',
            name='neckband',
        ),
        migrations.RemoveField(
            model_name='category',
            name='powerbank',
        ),
        migrations.RemoveField(
            model_name='category',
            name='smartphone',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tablet',
        ),
        migrations.RemoveField(
            model_name='category',
            name='watch',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
