# Generated by Django 4.2.14 on 2024-09-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0008_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productid',
        ),
        migrations.AddField(
            model_name='product',
            name='batterycapacity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='displaytype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='internalstoragetorage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inthebox',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='memorycardslottype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='operatingsystem',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='primarycamera',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processorbrand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supportednetworks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warrantysummary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
