# Generated by Django 4.2.14 on 2024-09-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0010_alter_product_inthebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inthebox',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
