# Generated by Django 4.2.14 on 2024-09-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0011_alter_product_description_alter_product_inthebox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='internalstoragetorage',
            new_name='internalstorage',
        ),
    ]
