# Generated by Django 5.1.1 on 2024-10-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0013_deliverydetails_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='order_id',
            field=models.CharField(max_length=220),
        ),
    ]
