# Generated by Django 5.1.1 on 2024-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0016_deliverydetails_customer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=500)),
                ('customer_city', models.CharField(max_length=50, null=True)),
                ('customer_state', models.CharField(max_length=50, null=True)),
                ('customer_contact', models.CharField(max_length=50)),
                ('customer_pincode', models.CharField(max_length=6)),
                ('customer_email', models.CharField(max_length=225)),
                ('productname', models.CharField(max_length=255)),
                ('productquantity', models.CharField(max_length=255)),
                ('productprice', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=225)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliverydetails',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='deliverydetails',
            name='order_id',
        ),
    ]
