# Generated by Django 5.1.1 on 2024-10-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0017_order_remove_deliverydetails_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
