# Generated by Django 5.1.1 on 2024-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0018_remove_order_id_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
    ]
