# Generated by Django 5.1.1 on 2024-10-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0019_alter_order_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
