# Generated by Django 5.1.1 on 2024-10-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0020_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=500)),
                ('customer_city', models.CharField(max_length=50, null=True)),
                ('customer_state', models.CharField(max_length=50, null=True)),
                ('customer_contact', models.CharField(max_length=50)),
                ('customer_pincode', models.CharField(max_length=6)),
                ('customer_email', models.CharField(max_length=225)),
                ('productname', models.CharField(max_length=255)),
                ('productquantity', models.CharField(max_length=255)),
                ('productprice', models.CharField(max_length=255)),
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
    ]
