# Generated by Django 5.1.1 on 2024-10-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0021_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
    ]
