# Generated by Django 5.1.1 on 2024-10-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0022_remove_order_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
