# Generated by Django 5.1.1 on 2024-10-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrihari', '0024_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
